#!/bin/bash

hosts=(ec2-54-174-6-90.compute-1.amazonaws.com
ec2-54-149-9-25.us-west-2.compute.amazonaws.com
ec2-54-67-86-61.us-west-1.compute.amazonaws.com
ec2-54-72-167-104.eu-west-1.compute.amazonaws.com
ec2-54-93-182-67.eu-central-1.compute.amazonaws.com
ec2-54-169-146-226.ap-southeast-1.compute.amazonaws.com
ec2-54-65-104-220.ap-northeast-1.compute.amazonaws.com
ec2-54-66-212-131.ap-southeast-2.compute.amazonaws.com
ec2-54-94-156-232.sa-east-1.compute.amazonaws.com
)

# parse command line arguments
while getopts "u:i:p::o::n::" opt; do
    case $opt in
    p)
      port=$OPTARG
      ;;
    o)
      origin=$OPTARG
      ;;
    n)
      name=$OPTARG
      ;;
    u)
      username=$OPTARG
      ;;
    i)
      keyfile=$OPTARG
      ;;
    esac
done

for host in "${hosts[@]}"
do
    echo "--------------------"
    echo "Running" $host
    ssh -i $keyfile $username@$host "cd ~/CDN/; chmod 700 runhttp; nohup ./runhttp -p $port -o $origin > /dev/null 2>&1 & "
done

dnsserver=cs5700cdnproject.ccs.neu.edu
echo "--------------------"
echo "Running " $dnsserver
ssh -i $keyfile $username@$dnsserver "cd ~/CDN/; chmod 700 rundns; nohup ./rundns -p $port -n $name > /dev/null 2>&1 &"

