#!/bin/bash

# parse command line arguments
while getopts "u:i:p::o::n::" opt; do
    case $opt in
    p)
	port=$OPTARG
	;;
    n)
	name=$OPTARG
	;;
    esac
done

# echo $port
# echo $((port+2))
# echo $name

python map.py $((port+2)) &
./dnsserver -p $port -n $name
