#!/bin/bash

# parse command line arguments
while getopts "u:i:p::o::n::" opt; do
    case $opt in
    p)
        port=$OPTARG
        ;;
    o)
        origin=$OPTARG
        ;;
    esac
done

python pinger.py $((port+2)) &  
./httpserver -p $port -o $origin &
